# Generated by Django 6.1 on 2026-08-29 15:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bloodinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloodrequest',
            name='accepted_donor',
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='accepted_donors',
            field=models.ManyToManyField(blank=True, related_name='accepted_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_fulfilled',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('FULFILLED', 'Fulfilled'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
