# Generated by Django 5.2.6 on 2026-10-08 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_profile_address_profile_helpline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('attendant_name', models.CharField(help_text='Family member or attendant donating blood', max_length=255)),
                ('contact_number', models.CharField(max_length=30)),
                ('required_blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], help_text='Blood group patient needs', max_length=3)),
                ('offered_blood_group', models.CharField(choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative')], help_text='Blood group attendant is donating in replacement', max_length=3)),
                ('units', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved for Exchange'), ('COMPLETED', 'Completed & Exchanged'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('urgency', models.CharField(choices=[('ROUTINE', 'Routine (Next week)'), ('HIGH', 'High (Today)'), ('CRITICAL', 'Critical (Within 2 hours)')], default='CRITICAL', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_requests', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='my_exchange_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
